services:
  devcontainer:
    build: .
    volumes:
      - ../.:/workspace:cached
      - ../src:/var/www/html
      - ../nginx.conf:/etc/nginx/nginx.conf:ro
      - ~/.ssh:/home/user/.ssh:ro
    ports:
      - 80:80